import assert from "node:assert/strict";
import { createHash, generateKeyPairSync, randomUUID, sign, verify } from "node:crypto";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";import path from "node:path";import test from "node:test";
import { ConnectorService, type DeviceAuth } from "../src/connector.js";import { AtlasDatabase } from "../src/db.js";
async function fixture(){const root=await mkdtemp(path.join(tmpdir(),"atlas-connector-"));await mkdir(path.join(root,"migrations"));for(const name of ["001_bootstrap.sql","006_m3_connector.sql"])await writeFile(path.join(root,"migrations",name),await readFile(path.join(process.cwd(),"migrations",name)));const previous=process.cwd();process.chdir(root);const db=new AtlasDatabase(path.join(root,"atlas.db"));process.chdir(previous);return{root,db,connector:new ConnectorService(db,root)};}
function signed(deviceId:string,privateKey:string,body:unknown,nonce=randomUUID()):DeviceAuth{const timestamp=new Date().toISOString();const digest=createHash("sha256").update(JSON.stringify(body??{})).digest("hex");return{deviceId,timestamp,nonce,signature:sign(null,Buffer.from([deviceId,timestamp,nonce,digest].join("\n")),privateKey).toString("base64url")};}
test("single-use enrollment assigns one Manager and signed commands",async()=>{const{db,connector}=await fixture();const invitation=connector.createEnrollment({name:"Remote laptop"});const keys=generateKeyPairSync("ed25519");const publicKey=keys.publicKey.export({type:"spki",format:"pem"}).toString(),privateKey=keys.privateKey.export({type:"pkcs8",format:"pem"}).toString();const enrolled=connector.enroll({token:invitation.token,publicKey,capabilities:{cpuCores:4}});assert.equal(db.all("SELECT * FROM managers WHERE environment_id=?",enrolled.environmentId).length,1);assert.throws(()=>connector.enroll({token:invitation.token,publicKey}),/already-used/);const queued=connector.queueCommand({environmentId:enrolled.environmentId,type:"inspect",capabilities:["system.inspect"],ttlSeconds:30});const auth=signed(enrolled.deviceId,privateKey,{});const polled=connector.poll(auth);assert.equal(polled.commands[0]?.id,queued.id);const command=polled.commands[0]!;const unsigned={id:command.id,environmentId:command.environmentId,sequence:command.sequence,type:command.type,payload:command.payload,capabilities:command.capabilities,expiresAt:command.expiresAt};assert.equal(verify(null,Buffer.from(JSON.stringify(unsigned)),enrolled.controlPlanePublicKey,Buffer.from(command.signature,"base64url")),true);assert.throws(()=>connector.poll(auth),/Replay detected/);db.close();});
test("telemetry is idempotent, reconnect-safe, and revocation blocks commands",async()=>{const{db,connector}=await fixture();const invitation=connector.createEnrollment({name:"Field computer"});const keys=generateKeyPairSync("ed25519"),publicKey=keys.publicKey.export({type:"spki",format:"pem"}).toString(),privateKey=keys.privateKey.export({type:"pkcs8",format:"pem"}).toString();const enrolled=connector.enroll({token:invitation.token,publicKey});const event={id:randomUUID(),type:"heartbeat",payload:{ok:true},occurredAt:new Date().toISOString()};const body={events:[event],health:{status:"online"}};assert.deepEqual(connector.telemetry(signed(enrolled.deviceId,privateKey,body),body),{accepted:1,duplicates:0});assert.deepEqual(connector.telemetry(signed(enrolled.deviceId,privateKey,body),body),{accepted:0,duplicates:1});connector.revoke(enrolled.environmentId);assert.throws(()=>connector.queueCommand({environmentId:enrolled.environmentId,type:"ping"}),/no active connector/);assert.throws(()=>connector.poll(signed(enrolled.deviceId,privateKey,{})),/revoked/);db.close();});
