import { createHash, randomBytes, verify } from "node:crypto";
import type { AtlasDatabase } from "./db.js";import { id,json,now,parseJson } from "./util.js";
type Row=Record<string,any>;export type BrowserAuth={sessionId:string;timestamp:string;nonce:string;signature:string};
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");const canonical=(a:Omit<BrowserAuth,"signature">,body:unknown)=>[a.sessionId,a.timestamp,a.nonce,hash(json(body??{}))].join("\n");
const allowed=new Set(["inspect","screenshot","click","type","select","scroll","navigate","downloads","errors","start_recording","stop_recording","rehearse"]);
function redact(value:any):any{if(Array.isArray(value))return value.map(redact);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([k,v])=>[/password|cookie|authorization|token|secret/i.test(k)?k:k,/password|cookie|authorization|token|secret/i.test(k)?"[REDACTED]":redact(v)]));return value;}
export class BrowserBridgeService{
 constructor(private readonly db:AtlasDatabase){}
 createPairing(input:{environmentId:string}){const manager=this.db.get<Row>("SELECT * FROM managers WHERE environment_id=?",input.environmentId);if(!manager)throw new Error("Environment has no Manager.");const token=randomBytes(24).toString("base64url"),expiresAt=new Date(Date.now()+10*60000).toISOString();this.db.run("INSERT INTO browser_pair_tokens(id,environment_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)",id("browser_pair"),input.environmentId,hash(token),expiresAt,now());return{token,expiresAt,environmentId:input.environmentId};}
 pair(input:{token:string;publicKey:string;tabRef:string;title:string;url:string}){const pair=this.db.get<Row>("SELECT * FROM browser_pair_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>?",hash(String(input.token??"")),now());if(!pair)throw new Error("Invalid, expired, or used browser pairing token.");if(!/^https?:|^chrome:/.test(input.url))throw new Error("Only a visible browser tab can be paired.");try{verify(null,Buffer.from("probe"),input.publicKey,Buffer.alloc(64));}catch{throw new Error("A valid Ed25519 browser public key is required.");}const manager=this.db.get<Row>("SELECT * FROM managers WHERE environment_id=?",pair.environment_id)!;const sessionId=id("browser");this.db.transaction(()=>{this.db.run("UPDATE browser_pair_tokens SET used_at=? WHERE id=?",now(),pair.id);this.db.run("INSERT INTO browser_sessions(id,environment_id,manager_id,public_key,tab_ref,title,url,status,consented_at,last_seen_at) VALUES(?,?,?,?,?,?,?,?,?,?)",sessionId,pair.environment_id,manager.id,input.publicKey,String(input.tabRef),String(input.title).slice(0,200),String(input.url).slice(0,2000),"connected",now(),now());});this.audit(manager.id,"browser.session.connected",sessionId,{title:input.title,url:input.url});return{sessionId,environmentId:pair.environment_id,managerId:manager.id,pollAfterMs:750};}
 authenticate(auth:BrowserAuth,body:unknown){const session=this.db.get<Row>("SELECT * FROM browser_sessions WHERE id=?",auth.sessionId);if(!session||session.status!=="connected")throw new Error("Browser session is disconnected or revoked.");const stamp=new Date(auth.timestamp).getTime();if(!Number.isFinite(stamp)||Math.abs(Date.now()-stamp)>300000)throw new Error("Browser request timestamp is outside the allowed window.");if(this.db.get("SELECT 1 FROM browser_nonces WHERE session_id=? AND nonce=?",auth.sessionId,auth.nonce))throw new Error("Browser request replay detected.");const unsigned={sessionId:auth.sessionId,timestamp:auth.timestamp,nonce:auth.nonce};if(!verify(null,Buffer.from(canonical(unsigned,body)),session.public_key,Buffer.from(auth.signature,"base64url")))throw new Error("Invalid browser signature.");this.db.run("INSERT INTO browser_nonces(session_id,nonce,seen_at) VALUES(?,?,?)",auth.sessionId,auth.nonce,now());return session;}
 queue(input:{sessionId:string;managerId:string;action:string;args?:unknown}){if(!allowed.has(input.action))throw new Error("Browser action is not allowed.");const session=this.db.get<Row>("SELECT * FROM browser_sessions WHERE id=?",input.sessionId);if(!session||session.status!=="connected")throw new Error("Browser session is disconnected or revoked.");if(session.manager_id!==input.managerId)throw new Error("Only the environment Manager may operate this browser session.");const commandId=id("browser_cmd");this.db.run("INSERT INTO browser_commands(id,session_id,manager_id,action,args_json,status,created_at) VALUES(?,?,?,?,?,?,?)",commandId,input.sessionId,input.managerId,input.action,json(redact(input.args??{})),"queued",now());this.audit(input.managerId,"browser.action.queued",input.sessionId,{commandId,action:input.action});return{id:commandId,sessionId:input.sessionId,action:input.action,status:"queued"};}
 poll(auth:BrowserAuth){const session=this.authenticate(auth,{});this.db.run("UPDATE browser_sessions SET last_seen_at=? WHERE id=?",now(),session.id);const commands=this.db.all<Row>("SELECT * FROM browser_commands WHERE session_id=? AND status IN ('queued','delivered') ORDER BY created_at LIMIT 10",session.id).map(row=>({id:row.id,action:row.action,args:parseJson(row.args_json)}));for(const command of commands)this.db.run("UPDATE browser_commands SET status='delivered',delivered_at=COALESCE(delivered_at,?) WHERE id=?",now(),command.id);return{commands};}
 events(auth:BrowserAuth,input:{events:Array<{id:string;commandId?:string;type:string;payload?:unknown;occurredAt:string}>}){const session=this.authenticate(auth,input);const encoded=json(input);if(encoded.length>1_500_000)throw new Error("Browser event batch is too large.");let accepted=0,duplicates=0;this.db.transaction(()=>{for(const event of input.events??[]){if(this.db.get("SELECT 1 FROM browser_events WHERE id=?",event.id)){duplicates++;continue;}const payload=redact(event.payload??{});this.db.run("INSERT INTO browser_events(id,session_id,command_id,type,payload_json,occurred_at,received_at) VALUES(?,?,?,?,?,?,?)",event.id,session.id,event.commandId??null,event.type,json(payload),event.occurredAt,now());if(event.commandId)this.db.run("UPDATE browser_commands SET status=?,completed_at=? WHERE id=? AND session_id=?",event.type==="command.failed"?"failed":"completed",now(),event.commandId,session.id);accepted++;}this.db.run("UPDATE browser_sessions SET last_seen_at=? WHERE id=?",now(),session.id);});this.audit(session.manager_id,"browser.events.received",session.id,{accepted,duplicates});return{accepted,duplicates};}
 disconnect(sessionId:string,status:"disconnected"|"revoked"="disconnected"){const session=this.db.get<Row>("SELECT * FROM browser_sessions WHERE id=?",sessionId);if(!session)throw new Error("Browser session not found.");const timestamp=now(),column=status==="revoked"?"revoked_at":"disconnected_at";this.db.transaction(()=>{this.db.run(`UPDATE browser_sessions SET status=?,${column}=? WHERE id=?`,status,timestamp,sessionId);this.db.run("UPDATE browser_commands SET status='cancelled' WHERE session_id=? AND status IN ('queued','delivered')",sessionId);});this.audit(session.manager_id,"browser.session."+status,sessionId,{});return{sessionId,status};}
 state(){return{sessions:this.db.all("SELECT id,environment_id,manager_id,tab_ref,title,url,status,consented_at,last_seen_at,disconnected_at,revoked_at FROM browser_sessions ORDER BY consented_at DESC"),commands:this.db.all("SELECT id,session_id,manager_id,action,status,created_at,delivered_at,completed_at FROM browser_commands ORDER BY created_at DESC LIMIT 50"),events:this.db.all("SELECT * FROM browser_events ORDER BY received_at DESC LIMIT 100")};}
 private audit(managerId:string,action:string,sessionId:string,detail:unknown){this.db.run("INSERT INTO audit_events(actor_type,actor_id,action,entity_type,entity_id,detail_json,created_at) VALUES(?,?,?,?,?,?,?)","manager",managerId,action,"browser_session",sessionId,json(redact(detail)),now());}
}
