#!/usr/bin/env node
import { generateKeyPairSync, randomUUID, sign, verify } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import os from "node:os";import path from "node:path";
const args=Object.fromEntries(process.argv.slice(2).map((v,i,a)=>v.startsWith("--")?[v.slice(2),a[i+1]]:null).filter(Boolean) as Array<[string,string]>);
const server=String(args.server??process.env.ATLAS_URL??"").replace(/\/$/,"");const token=String(args.token??process.env.ATLAS_ENROLLMENT_TOKEN??"");
if(!server)throw new Error("--server is required.");if(!/^https:\/\//.test(server)&&!/^http:\/\/(127\.0\.0\.1|localhost)(:|\/|$)/.test(server))throw new Error("Remote ATLAS connections require HTTPS.");
const dir=path.resolve(String(args.data??path.join(os.homedir(),".atlas-runtime")));mkdirSync(dir,{recursive:true});const identityFile=path.join(dir,"identity.json"),queueFile=path.join(dir,"events.json");
let identity:any;if(existsSync(identityFile))identity=JSON.parse(readFileSync(identityFile,"utf8"));else{if(!token)throw new Error("--token is required for first enrollment.");const pair=generateKeyPairSync("ed25519");const privateKey=pair.privateKey.export({type:"pkcs8",format:"pem"}).toString(),publicKey=pair.publicKey.export({type:"spki",format:"pem"}).toString();const response=await fetch(server+"/api/connectors/enroll",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,publicKey,capabilities:{hostname:os.hostname(),platform:os.platform(),cpuCores:os.cpus().length,totalMemoryBytes:os.totalmem()}})});if(!response.ok)throw new Error(await response.text());identity={...(await response.json()),privateKey};writeFileSync(identityFile,JSON.stringify(identity,null,2),{mode:0o600});}
let events:any[]=existsSync(queueFile)?JSON.parse(readFileSync(queueFile,"utf8")):[];const persist=()=>{const tmp=queueFile+".tmp";writeFileSync(tmp,JSON.stringify(events));renameSync(tmp,queueFile);};
const auth=(body:unknown)=>{const timestamp=new Date().toISOString(),nonce=randomUUID();const h=requireHash(JSON.stringify(body??{}));const message=[identity.deviceId,timestamp,nonce,h].join("\n");return {deviceId:identity.deviceId,timestamp,nonce,signature:sign(null,Buffer.from(message),identity.privateKey).toString("base64url")};};
function requireHash(value:string){return (globalThis as any).__hash(value)}
const crypto=await import("node:crypto");(globalThis as any).__hash=(value:string)=>crypto.createHash("sha256").update(value).digest("hex");
async function post(route:string,body:unknown){const response=await fetch(server+route,{method:"POST",headers:{"content-type":"application/json","x-atlas-device-auth":Buffer.from(JSON.stringify(auth(body))).toString("base64url")},body:JSON.stringify(body)});if(!response.ok)throw new Error(await response.text());return response.json();}
async function cycle(){try{if(events.length){const result=await post("/api/connectors/telemetry",{events,health:{status:"online",workload:0,recovery:"connected",checkedAt:new Date().toISOString()}});events.splice(0,result.accepted+result.duplicates);persist();}const result=await post("/api/connectors/poll",{});for(const command of result.commands){const unsigned={id:command.id,environmentId:command.environmentId,sequence:command.sequence,type:command.type,payload:command.payload,capabilities:command.capabilities,expiresAt:command.expiresAt};if(!verify(null,Buffer.from(JSON.stringify(unsigned)),identity.controlPlanePublicKey,Buffer.from(command.signature,"base64url")))continue;if(new Date(command.expiresAt).getTime()<Date.now())continue;let payload:any;try{if(command.type==="inspect")payload={hostname:os.hostname(),platform:os.platform(),freeMemoryBytes:os.freemem(),uptimeSeconds:os.uptime()};else if(command.type==="ping")payload={pong:true};else throw new Error("Unsupported command type");events.push({id:randomUUID(),commandId:command.id,type:"command.completed",payload,occurredAt:new Date().toISOString()});}catch(error){events.push({id:randomUUID(),commandId:command.id,type:"command.failed",payload:{error:error instanceof Error?error.message:"Unknown error"},occurredAt:new Date().toISOString()});}persist();}}catch(error){console.error("Connector offline; buffered events retained:",error instanceof Error?error.message:error);}}
await cycle();setInterval(cycle,Number(args.interval??2000));console.log("ATLAS environment runtime connected:",identity.environmentId);
