import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import type { AtlasDatabase } from "./db.js";
import { id, now } from "./util.js";
type Row = Record<string, any>;
const providers = new Set(["ollama", "groq", "openrouter", "openai"]);
export class SettingsService {
 private readonly key:Buffer; private readonly backupDir:string;
 constructor(private readonly db:AtlasDatabase,root=process.cwd()){const dataDir=path.join(root,"data");mkdirSync(dataDir,{recursive:true});const keyPath=path.join(dataDir,".atlas-master-key");if(!existsSync(keyPath))writeFileSync(keyPath,randomBytes(32),{flag:"wx",mode:0o600});this.key=readFileSync(keyPath);if(this.key.length!==32)throw new Error("ATLAS secret key is invalid.");this.backupDir=path.join(dataDir,"backups");mkdirSync(this.backupDir,{recursive:true});this.bootstrap();}
 private bootstrap(){const row=this.db.get<Row>("SELECT * FROM platform_settings WHERE id='default'");const provider=process.env.ATLAS_MODEL_PROVIDER?.toLowerCase();if(row?.updated_at&&!row.updated_at.includes(" "))return;if(provider&&providers.has(provider))this.db.run("UPDATE platform_settings SET provider=?,model=?,base_url=?,timeout_ms=?,updated_at=? WHERE id='default'",provider,process.env.ATLAS_MODEL??row?.model??"qwen3:4b",provider==="ollama"?process.env.OLLAMA_BASE_URL??"http://127.0.0.1:11434":null,Number(process.env.OLLAMA_TIMEOUT_MS??120000),now());}
 state(){const setting=this.db.get<Row>("SELECT * FROM platform_settings WHERE id='default'")!;const modelRoles=this.db.all<Row>("SELECT * FROM model_role_settings ORDER BY role");const secrets=this.db.all<Row>("SELECT id,provider,label,status,created_at,rotated_at,tested_at FROM secret_references ORDER BY created_at DESC");const permissions=this.db.all<Row>("SELECT * FROM environment_permissions").map(row=>({...row,tools:JSON.parse(row.tools_json)}));const backups=this.db.all<Row>("SELECT * FROM system_backups ORDER BY created_at DESC LIMIT 10");return{setting,modelRoles,secrets,permissions,backups,restart:{available:false,explanation:"Automatic restart requires the signed service installer planned for M9. Provider changes apply immediately."},recovery:{available:false,explanation:"Backups are created and verified here. In-place restore is disabled while ATLAS is running to protect active data."}};}
 saveProvider(input:any){const provider=String(input.provider??"").toLowerCase();if(!providers.has(provider))throw new Error("Unsupported model provider.");const model=String(input.model??"").trim();if(!model||model.length>160)throw new Error("Model is required.");const secretRefId=input.secretRefId?String(input.secretRefId):null;if(provider!=="ollama"&&!this.db.get("SELECT id FROM secret_references WHERE id=? AND provider=? AND status='active'",secretRefId,provider))throw new Error("Select an active secret reference for this provider.");const baseUrl=input.baseUrl?String(input.baseUrl).trim():null;if(baseUrl&&!/^https?:\/\//.test(baseUrl))throw new Error("Provider address must start with http:// or https://.");const timeout=Math.min(600000,Math.max(5000,Number(input.timeoutMs??120000)));this.db.run("UPDATE platform_settings SET provider=?,model=?,base_url=?,secret_ref_id=?,timeout_ms=?,fallback_enabled=0,updated_at=? WHERE id='default'",provider,model,baseUrl,secretRefId,timeout,now());return this.db.get<Row>("SELECT * FROM platform_settings WHERE id='default'")!;}
 saveRoleProvider(role:string,input:any){if(!["ada","operations"].includes(role))throw new Error("Model role must be ada or operations.");const provider=String(input.provider??"").toLowerCase();if(!providers.has(provider))throw new Error("Unsupported model provider.");const model=String(input.model??"").trim();if(!model||model.length>200)throw new Error("Model is required.");const secretRefId=input.secretRefId?String(input.secretRefId):null;if(provider!=="ollama"&&!this.db.get("SELECT id FROM secret_references WHERE id=? AND provider=? AND status='active'",secretRefId,provider))throw new Error("Select an active secret reference for this provider.");const baseUrl=input.baseUrl?String(input.baseUrl).trim():null;if(baseUrl&&!/^https?:\/\//.test(baseUrl))throw new Error("Provider address must start with http:// or https://.");const timeout=Math.min(600000,Math.max(5000,Number(input.timeoutMs??120000)));this.db.run("INSERT INTO model_role_settings(role,provider,model,base_url,secret_ref_id,timeout_ms,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(role) DO UPDATE SET provider=excluded.provider,model=excluded.model,base_url=excluded.base_url,secret_ref_id=excluded.secret_ref_id,timeout_ms=excluded.timeout_ms,updated_at=excluded.updated_at",role,provider,model,baseUrl,secretRefId,timeout,now());return this.db.get<Row>("SELECT * FROM model_role_settings WHERE role=?",role)!;}
 createSecret(input:any){const provider=String(input.provider??"").toLowerCase(),label=String(input.label??"").trim(),value=String(input.value??"");if(!providers.has(provider)||provider==="ollama")throw new Error("Secret provider must be Groq, OpenRouter, or OpenAI.");if(!label||label.length>120)throw new Error("Secret label is required.");if(value.length<8)throw new Error("Secret value is too short.");const e=this.encrypt(value),secretId=id("secret");this.db.run("INSERT INTO secret_references(id,provider,label,ciphertext,iv,auth_tag,status,created_at) VALUES(?,?,?,?,?,?,'active',?)",secretId,provider,label,e.ciphertext,e.iv,e.authTag,now());return this.metadata(secretId);}
 rotateSecret(secretId:string,value:unknown){if(!this.db.get("SELECT id FROM secret_references WHERE id=? AND status='active'",secretId))throw new Error("Active secret reference not found.");const plaintext=String(value??"");if(plaintext.length<8)throw new Error("Secret value is too short.");const e=this.encrypt(plaintext);this.db.run("UPDATE secret_references SET ciphertext=?,iv=?,auth_tag=?,rotated_at=?,tested_at=NULL WHERE id=?",e.ciphertext,e.iv,e.authTag,now(),secretId);return this.metadata(secretId);}
 revokeSecret(secretId:string){if(!this.db.get("SELECT id FROM secret_references WHERE id=?",secretId))throw new Error("Secret reference not found.");this.db.run("UPDATE secret_references SET status='revoked' WHERE id=?",secretId);return this.metadata(secretId);}
 getSecret(secretId:string|null){if(!secretId)return undefined;const row=this.db.get<Row>("SELECT * FROM secret_references WHERE id=? AND status='active'",secretId);return row?this.decrypt(row):undefined;} markTested(secretId:string|null){if(secretId)this.db.run("UPDATE secret_references SET tested_at=? WHERE id=?",now(),secretId);}
 saveEnvironmentPermissions(environmentId:string,input:any){if(!this.db.get("SELECT id FROM environments WHERE id=?",environmentId))throw new Error("Environment not found.");const allowed=new Set(["system.disk_space"]);const tools=Array.isArray(input.tools)?input.tools.filter((x:unknown)=>allowed.has(String(x))):[];const filesystem=["none","workspace"].includes(input.filesystemScope)?input.filesystemScope:"none";const network=input.networkEnabled===true?1:0;this.db.run("INSERT INTO environment_permissions(environment_id,tools_json,filesystem_scope,network_enabled,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(environment_id) DO UPDATE SET tools_json=excluded.tools_json,filesystem_scope=excluded.filesystem_scope,network_enabled=excluded.network_enabled,updated_at=excluded.updated_at",environmentId,JSON.stringify(tools),filesystem,network,now());return this.db.get<Row>("SELECT * FROM environment_permissions WHERE environment_id=?",environmentId)!;}
 createBackup(){const backupId=id("backup"),filename=`atlas-${new Date().toISOString().replace(/[:.]/g,"-")}.db`,target=path.join(this.backupDir,filename);this.db.db.exec("PRAGMA wal_checkpoint(FULL)");copyFileSync(this.db.file,target);const check=new DatabaseSync(target,{readOnly:true});const integrity=check.prepare("PRAGMA integrity_check").get() as Record<string,string>;check.close();const verified=Object.values(integrity).includes("ok");this.db.run("INSERT INTO system_backups(id,filename,status,size_bytes,created_at,verified_at) VALUES(?,?,?,?,?,?)",backupId,filename,verified?"verified":"failed",statSync(target).size,now(),verified?now():null);return this.db.get<Row>("SELECT * FROM system_backups WHERE id=?",backupId)!;}
 diagnostics(){const integrity=this.db.db.prepare("PRAGMA integrity_check").get() as Record<string,string>;return{databaseIntegrity:Object.values(integrity)[0],databaseBytes:statSync(this.db.file).size,node:process.version,platform:process.platform,uptimeSeconds:Math.round(process.uptime()),checkedAt:now()};}
 private metadata(id:string){return this.db.get<Row>("SELECT id,provider,label,status,created_at,rotated_at,tested_at FROM secret_references WHERE id=?",id)!;} private encrypt(value:string){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",this.key,iv),encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return{ciphertext:encrypted.toString("base64"),iv:iv.toString("base64"),authTag:cipher.getAuthTag().toString("base64")};} private decrypt(row:Row){const d=createDecipheriv("aes-256-gcm",this.key,Buffer.from(row.iv,"base64"));d.setAuthTag(Buffer.from(row.auth_tag,"base64"));return Buffer.concat([d.update(Buffer.from(row.ciphertext,"base64")),d.final()]).toString("utf8");}
}
